import { Movie } from "models/movie.model";

const movies: Movie[] = [
    {
      id: 1,
      title: "Intouchables",
      director: null,
      release_date: null,
      synopsis: `A la suite d’un accident de parapente, Philippe, riche aristocrate, engage comme aide à domicile Driss, un jeune de banlieue tout juste sorti de prison… Bref la personne la moins adaptée pour le job. Ensemble ils vont faire cohabiter Vivaldi et Earth Wind and Fire, le verbe et la vanne, les costumes et les bas de survêtement… Deux univers vont se téléscoper, s’apprivoiser, pour donner naissance à une amitié aussi dingue, drôle et forte qu’inattendue, une relation unique qui fera des étincelles et qui les rendra… Intouchables.`,
      poster_url:"assets/images/Intouchables.jpg",
      updated_at: null,
      created_at: "2024-05-04",
    },
    {
      id: 2,
      title: "La Communauté de l'Anneau",
      director: "Peter Jackson",
      release_date: "2001",
      synopsis: `Le Seigneur des anneaux : La Communauté de l'anneau (The Lord of The Rings: The Fellowship of the Ring) est un film américano-néo-zélandais réalisé par Peter Jackson, sorti en 2001. C'est le premier volet de la trilogie Le Seigneur des anneaux et l'adaptation du livre La Communauté de l'Anneau de J. R. R. Tolkien. L'histoire commence lorsque, sur la Terre du Milieu, le magicien Gandalf le Gris (Ian McKellen) découvre que l'anneau que possède le jeune Hobbit Frodon Sacquet (Elijah Wood), qui lui a été légué par son oncle Bilbon et qui lui permet de se rendre invisible, est en réalité l'Anneau unique recherché avidement par le seigneur ténébreux Sauron car il lui permettrait de retrouver toute sa puissance. Afin d'éviter que Sauron ne récupère l'anneau, Frodon et ses huit compagnons, la Communauté de l'Anneau, entament un périlleux voyage dans le but de le détruire...`,
      poster_url:"assets/images/la_communaute_de_lanneau.jpg",
      updated_at: null,
      created_at: "2024-05-04",
    },
    {
      id: 3,
      title: "Les Aventuriers de l'Arche Perdue",
      director: "Steven Spielberg",
      release_date: "1981",
      synopsis: `Les Aventuriers de l'arche perdue (Raiders of the Lost Ark) est un film d'aventure fantastique américain, réalisé par Steven Spielberg et co-produit par George Lucas, sorti en 1981. À partir de l'an 2000, il est exploité sous le nom Indiana Jones et les Aventuriers de l'arche perdue1 (Indiana Jones and the Raiders of the Lost Ark). Premier volet de la saga Indiana Jones (deuxième chronologiquement), Raiders of the Lost Ark a été nommé neuf fois aux Oscars 1982 et en a remporté cinq (dont un spécial pour les effets sonores).`,
      poster_url:"assets/images/les_aventuriers_arche_perdue.jpg",
      updated_at: null,
      created_at: "2024-05-04",
    },
    {
      id: 4,
      title: "La Guerre des Etoiles",
      director: "George Lucas",
      release_date: "1977",
      synopsis: `La Guerre des étoiles (Star Wars) est un film américain de science-fiction de type space opera sorti en 1977 écrit et réalisé par George Lucas. À partir de 2000, il est exploité sous le nom Star Wars, épisode IV : Un nouvel espoir (Star Wars: Episode IV – A New Hope). C'est le premier opus de la saga Star Wars par sa date de sortie, mais le quatrième selon l'ordre chronologique de l'histoire. Il est le premier volet de la trilogie originale qui est constituée également des films L'Empire contre-attaque et Le Retour du Jedi. Ce film est aussi le troisième long métrage réalisé par Lucas...`,
      poster_url:"assets/images/la_guerre_des_etoiles.jpg",
      updated_at: null,
      created_at: "2024-05-04",
    },
    {
      id: 5,
      title: "Les Deux Tours",
      director: "Peter Jackson",
      release_date: "2002",
      synopsis: `Le Seigneur des anneaux : Les Deux Tours (The Lord of the Rings: The Two Towers) est un film américano-néo-zélandais réalisé par Peter Jackson, sorti en 2002. Il est adapté du deuxième tome (1954) du roman Le Seigneur des anneaux, de l'écrivain britannique J. R. R. Tolkien. Dans la trilogie cinématographique de Peter Jackson, qui reproduit la trilogie du roman, le film suit La Communauté de l'anneau et précède Le Retour du roi. Le scénario du film a été écrit par Peter Jackson, son épouse Fran Walsh et Philippa Boyens, mais a été modifié en cours de tournage sur de nombreux points, avec l'aide et les idées des interprètes, et notamment pour répondre aux critiques formulées par les fans sur les informations qui avaient filtré sur Internet1. Le tournage a eu lieu en Nouvelle-Zélande, entre les années 1999 et 20002. L'histoire du film commence après la dissolution de la communauté de l'Anneau. Boromir est mort des mains du chef des Uruk-hai, Lurtz, en essayant de sauver les Hobbits Meriadoc Brandebouc et Peregrin Touque, qui ont été capturés. Aragorn, Gimli et Legolas poursuivent les Uruks afin de libérer leurs compagnons capturés, tandis que Frodon Sacquet et Samsagace Gamegie sont partis seuls pour le Mordor afin de détruire l'Anneau unique, à la Montagne du Destin...`,
      poster_url:"assets/images/les_deux_tours.jpg",
      updated_at: null,
      created_at: "2024-05-04",
    },
    {
      id: 6,
      title: "Le Retour du Roi",
      director: "Peter Jackson",
      release_date: "2003",
      synopsis: `Le Seigneur des anneaux : Le Retour du roi (The Lord of the Rings: The Return of the King) est un film américano-néo-zélandais réalisé par Peter Jackson, sorti en 2003. Adapté du livre Le Retour du roi de J. R. R. Tolkien, il incorpore également des événements du livre précédent, Les Deux Tours. C'est le troisième volet de la trilogie Le Seigneur des anneaux, après La Communauté de l'anneau et Les Deux Tours. Alors que Sauron lance ses armées à l'assaut de la Terre du Milieu, le magicien Gandalf et le roi Théoden réunissent leurs forces pour défendre la capitale du Gondor, Minas Tirith. Aragorn réclame son trône et fait appel à l'armée des Morts pour remporter la bataille des Champs du Pelennor. Pendant ce temps, les hobbits Frodon Sacquet et Samsagace Gamegie traversent le Mordor guidés par Gollum pour aller détruire l'Anneau unique à la montagne du Destin...`,
      poster_url:"assets/images/le_retour_du_roi.jpg",
      updated_at: null,
      created_at: "2024-05-04",
    },
    {
      id: 7,
      title: "L'Empire Contre Attaque",
      director: "Irvin Kershner",
      release_date: "1980",
      synopsis: `L'Empire contre-attaque (The Empire Strikes Back) est un film américain de science-fiction de type space opera sorti en 1980, co-écrit par George Lucas et Lawrence Kasdan, et réalisé par Irvin Kershner. À partir de l'année 2000, il est exploité sous le nom Star Wars, épisode V : L'Empire contre-attaque (Star Wars: Episode V – The Empire Strikes Back). C'est le deuxième opus de la saga Star Wars par sa date de sortie, mais le cinquième selon l'ordre chronologique de l'histoire. Il est le deuxième volet de la trilogie originale qui est constituée également des films Un nouvel espoir et Le Retour du Jedi. L'histoire de cet épisode se déroule trois ans après les événements d’Un nouvel espoir. La guerre entre le maléfique Empire galactique et son antagoniste, l’Alliance rebelle, bat son plein. Les héros de l’Alliance Luke Skywalker et Han Solo se séparent après la prise de la principale base rebelle par l’Empire. Luke part sur la planète Dagobah afin de suivre la formation de Jedi auprès du maître Yoda. Solo tente lui d’échapper à la chasse spatiale que lui mène Dark Vador, l’apprenti de l’Empereur Palpatine.`,
      poster_url:"assets/images/l_empire_contre_attaque.jpg",
      updated_at: null,
      created_at: "2024-05-04",
    },
    {
      id: 8,
      title: "Le Retour du Jedi",
      director: "Richard Marquand",
      release_date: "1983",
      synopsis: `Le Retour du Jedi (Return of the Jedi) est un film américain de science-fiction de type space opera sorti en 1983, co-écrit par George Lucas et Lawrence Kasdan, et réalisé par Richard Marquand. À partir de l'année 2000, il est exploité sous le nom Star Wars, épisode VI : Le Retour du Jedi (Star Wars: Episode VI – Return of the Jedi). C'est le troisième opus de la saga Star Wars par sa date de sortie, mais le sixième selon l'ordre chronologique de l'histoire. Il est le dernier volet de la trilogie originale qui est constituée également des films Un nouvel espoir et L'Empire contre-attaque. L'histoire de cet épisode se déroule un an après les événements de L'Empire contre-attaque. Le maléfique Empire galactique construit une nouvelle station spatiale Étoile de la mort pour anéantir définitivement l'Alliance rebelle, son opposition principale. Pour tendre un piège à la flotte ennemie, l'empereur Palpatine se rend sur la station encore vulnérable. Les dirigeants de l'Alliance lancent donc toutes leurs forces à l'assaut ne se doutant pas que la flotte impériale les attend de pied ferme. De son côté, le jeune Jedi Luke Skywalker, l'un des héros de l'Alliance veut sauver son père Dark Vador du côté obscur de la Force et le rallier à sa cause.`,
      poster_url:"assets/images/le_retour_du_jedi.jpg",
      updated_at: null,
      created_at: "2024-05-04",
    },
    {
      id: 9,
      title: "Indiana Jones et le Temple Maudit",
      director: "Steven Spielberg",
      release_date: "1984",
      synopsis: `C'est le deuxième volet de la série de quatre films centrés sur le personnage d'Indiana Jones. Son action se déroule en 1935 donc avant celle du premier volet Les Aventuriers de l'arche perdue située en 1936. Shanghai, 1935 : Indiana Jones arrive dans un bar appartenant à un gangster chinois, Lao Che. Il doit récupérer un diamant et l'échanger contre les cendres de Nurhachi, un empereur chinois. Mais l'échange tourne à la fusillade et Indiana, emportant avec lui Willie Scott, une meneuse de revue qui s'intéressait à la pierre, parvient à quitter la Chine avec l'aide de Demi-Lune, un petit garçon chinois de 11 ans débrouillard, à bord d'un avion. Mais l'avion appartient à Lao Che et les pilotes, après avoir vidé les réservoirs, sautent en parachute. Utilisant un canot de sauvetage pneumatique pour amortir leur chute, Indiana, Willie et Demi-Lune sautent de l'avion et parviennent à fuir...`,
      poster_url:"assets/images/le_temple_maudit.jpg",
      updated_at: null,
      created_at: "2024-05-04",
    },
    {
      id: 10,
      title: "Indiana Jones et la Dernière Croisade",
      director: "Steven Spielberg",
      release_date: "1989",
      synopsis: `Indiana Jones et la Dernière Croisade (Indiana Jones and the Last Crusade) est un film d'aventure fantastique américain réalisé par Steven Spielberg, sorti en 1989. Il s'agit du troisième volet de la série de quatre films centrés sur le personnage d'Indiana Jones incarné par Harrison Ford. Utah, 1912. Le jeune Indiana Jones (River Phoenix) fait partie d'une troupe de scouts quand il surprend des pilleurs de tombes dans une grotte. Il leur dérobe un objet précieux, la croix de Coronado, et leur échappe après une longue poursuite, mais il se voit contraint de la leur restituer un peu plus tard...`,
      poster_url:"assets/images/la_derniere_croisade.jpg",
      updated_at: null,
      created_at: "2024-05-04",
    },
    {
      id: 11,
      title: "Pulp Fiction",
      director: "Quentin Tarantino",
      release_date: "1994",
      synopsis: `Pulp Fiction est un film policier et une comédie noire américaine réalisé par Quentin Tarantino et sorti en 1994. Il est considéré comme l'un des meilleurs films de tous les temps. Le film mêle plusieurs histoires ayant pour protagonistes différents personnages criminels de Los Angeles. L'intrigue est présentée de manière chronologiquement désordonnée et comprend des scènes de violence, d'humour noir et de dialogues riches en références culturelles. Pulp Fiction a remporté la Palme d'or au Festival de Cannes 1994, deux Oscars (meilleur scénario original pour Tarantino et Roger Avary et meilleur second rôle masculin pour Samuel L. Jackson) ainsi que de nombreux autres prix et nominations.`,
      poster_url:"assets/images/pulp_fiction.jpg",
      updated_at: null,
      created_at: "2024-05-04",
    },
    {
      id: 12,
      title: "Forrest Gump",
      director: "Robert Zemeckis",
      release_date: "1994",
      synopsis: `Forrest Gump est une comédie dramatique américaine réalisée par Robert Zemeckis, sortie en 1994. Le film est l'adaptation du roman du même nom de Winston Groom, publié en 1986. L'histoire est celle de Forrest Gump, un homme simple d'esprit, qui traverse l'histoire des États-Unis des années 1960 aux années 1980. Malgré son handicap mental, il se retrouve impliqué dans de nombreux événements marquants de l'époque. Le film met en vedette Tom Hanks dans le rôle-titre, ainsi que Robin Wright, Gary Sinise et Sally Field.`,
      poster_url:"assets/images/forrest_gump.jpg",
      updated_at: null,
      created_at: "2024-05-04",
    },
    {
      id: 13,
      title: "Inception",
      director: "Christopher Nolan",
      release_date: "2010",
      synopsis: `Inception est un thriller de science-fiction américano-britannique écrit, produit et réalisé par Christopher Nolan, sorti en 2010. Le film, qui se déroule dans l'architecture de l'esprit humain, explore le thème des rêves et met en vedette un ensemble de personnages qui tentent de voler des secrets industriels en utilisant une technologie qui permet l'infiltration de l'esprit d'une personne et le vol de ses secrets les plus intimes. Leonardo DiCaprio tient le rôle principal du « voleur » Dom Cobb. Inception est réputé pour son scénario complexe, ses effets visuels spectaculaires et sa bande-son, et a été largement acclamé par la critique.`,
      poster_url:"assets/images/inception.jpg",
      updated_at: null,
      created_at: "2024-05-04",
    },
    {
      id: 14,
      title: "Le Parrain",
      director: "Francis Ford Coppola",
      release_date: "1972",
      synopsis: `Le Parrain (The Godfather) est un film américain réalisé par Francis Ford Coppola et produit par les studios Paramount, sorti en 1972. Il s'agit d'une adaptation du roman éponyme de Mario Puzo. Le film met en vedette Marlon Brando dans le rôle de Don Vito Corleone, le patriarche de la famille mafieuse Corleone de New York. Le Parrain est devenu une référence dans la culture populaire, largement considéré comme l'un des meilleurs films jamais réalisés. Il a remporté trois Oscars, dont celui du meilleur film, et a été suivi de deux suites, Le Parrain 2 en 1974 et Le Parrain 3 en 1990.`,
      poster_url:"assets/images/le_parrain.jpg",
      updated_at: null,
      created_at: "2024-05-04",
    },
    {
      id: 15,
      title: "Le Seigneur des Anneaux: La Communauté de l'Anneau",
      director: "Peter Jackson",
      release_date: "2001",
      synopsis: `Le Seigneur des anneaux : La Communauté de l'anneau (The Lord of The Rings: The Fellowship of the Ring) est un film américano-néo-zélandais réalisé par Peter Jackson, sorti en 2001. C'est le premier volet de la trilogie Le Seigneur des anneaux et l'adaptation du livre La Communauté de l'Anneau de J. R. R. Tolkien. L'histoire commence lorsque, sur la Terre du Milieu, le magicien Gandalf le Gris (Ian McKellen) découvre que l'anneau que possède le jeune Hobbit Frodon Sacquet (Elijah Wood), qui lui a été légué par son oncle Bilbon et qui lui permet de se rendre invisible, est en réalité l'Anneau unique recherché avidement par le seigneur ténébreux Sauron car il lui permettrait de retrouver toute sa puissance. Afin d'éviter que Sauron ne récupère l'anneau, Frodon et ses huit compagnons, la Communauté de l'Anneau, entament un périlleux voyage dans le but de le détruire...`,
      poster_url:"assets/images/la_communaute_de_lanneau.jpg",
      updated_at: null,
      created_at: "2024-05-04",
    },
  ];

  export default movies;
