

export const reviews = [
  {
    "id": 1,
    "user_id": 3,
    "entity_id": 7,
    "entity_type": "movie",
    "rating": 4,
    "full_name": "John Doe",
    "email": "john@example.com",
    "summary": "Great movie!",
    "review": "I really enjoyed watching this movie. It had a great storyline and amazing performances.",
    "image": "https://example.com/image1.jpg",
    "updatedAt": "2024-05-05T12:00:00Z",
    "createdAt": "2024-05-05T10:30:00Z"
  },
  {
    "id": 2,
    "user_id": 8,
    "entity_id": 4,
    "entity_type": "place",
    "rating": 5,
    "full_name": "Alice Smith",
    "email": "alice@example.com",
    "summary": "Fantastic experience!",
    "review": "I visited this place with my family and we had an amazing time. The staff was friendly and the atmosphere was great.",
    "image": null,
    "updatedAt": null,
    "createdAt": "2024-05-04T15:45:00Z"
  },
  {
    "id": 3,
    "user_id": 12,
    "entity_id": 9,
    "entity_type": "movie",
    "rating": 3,
    "full_name": "Emma Johnson",
    "email": "emma@example.com",
    "summary": null,
    "review": "The movie was okay. It didn't quite meet my expectations.",
    "image": null,
    "updatedAt": null,
    "createdAt": "2024-05-03T09:20:00Z"
  },
  {
    "id": 4,
    "user_id": 6,
    "entity_id": 2,
    "entity_type": "place",
    "rating": 4,
    "full_name": "Michael Brown",
    "email": "michael@example.com",
    "summary": "Nice place to visit",
    "review": "I had a pleasant experience visiting this place. Would recommend it to others.",
    "image": "https://example.com/image2.jpg",
    "updatedAt": null,
    "createdAt": "2024-05-02T18:10:00Z"
  },
  {
    "id": 5,
    "user_id": 9,
    "entity_id": 5,
    "entity_type": "movie",
    "rating": 5,
    "full_name": "Sophia Wilson",
    "email": "sophia@example.com",
    "summary": "Must-watch!",
    "review": "This movie is a must-watch! It kept me engaged from start to finish.",
    "image": null,
    "updatedAt": "2024-05-01T14:20:00Z",
    "createdAt": "2024-04-30T20:05:00Z"
  },
  {
    "id": 6,
    "user_id": 15,
    "entity_id": 1,
    "entity_type": "place",
    "rating": 3,
    "full_name": "David Lee",
    "email": "david@example.com",
    "summary": null,
    "review": "The place was nice but a bit crowded. Overall, it was an okay experience.",
    "image": null,
    "updatedAt": null,
    "createdAt": "2024-04-29T12:30:00Z"
  },
  {
    "id": 7,
    "user_id": 5,
    "entity_id": 8,
    "entity_type": "movie",
    "rating": 4,
    "full_name": "Olivia Martinez",
    "email": "olivia@example.com",
    "summary": "Enjoyable movie",
    "review": "I enjoyed watching this movie with my friends. It had some unexpected twists.",
    "image": "https://example.com/image3.jpg",
    "updatedAt": "2024-04-28T16:40:00Z",
    "createdAt": "2024-04-27T21:15:00Z"
  },
  {
    "id": 8,
    "user_id": 11,
    "entity_id": 3,
    "entity_type": "place",
    "rating": 2,
    "full_name": "James Rodriguez",
    "email": "james@example.com",
    "summary": "Disappointing experience",
    "review": "I was disappointed with my experience at this place. The service was slow and the food was not good.",
    "image": null,
    "updatedAt": "2024-04-26T11:55:00Z",
    "createdAt": "2024-04-25T17:30:00Z"
  },
  {
    "id": 9,
    "user_id": 14,
    "entity_id": 6,
    "entity_type": "movie",
    "rating": 5,
    "full_name": "Isabella Garcia",
    "email": "isabella@example.com",
    "summary": null,
    "review": "Absolutely loved this movie! It was one of the best movies I've seen in a while.",
    "image": null,
    "updatedAt": "2024-04-24T09:10:00Z",
    "createdAt": "2024-04-23T22:25:00Z"
  },
  {
    "id": 10,
    "user_id": 2,
    "entity_id": 10,
    "entity_type": "place",
    "rating": 4,
    "full_name": "William Brown",
    "email": "william@example.com",
    "summary": "Good place for a family outing",
    "review": "Visited this place with my family and we had a great time. The facilities were clean and well-maintained.",
    "image": "https://example.com/image4.jpg",
    "updatedAt": "2024-04-22T13:20:00Z",
    "createdAt": "2024-04-21T18:45:00Z"
  }
]
