version: '3.1'
services:
  database:
    container_name: api_database
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5431:5432"